#Spring JPA
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bioauth_2
    username: accmanager
    password: accmanager
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        jdbc:
          time_zone: +03:00
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 8082